services:
  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: nodejs-server
    container_name: ${PROJECT_NAME}-server
    restart: unless-stopped
    env_file: .env
    ports:
      - '${SERVER_PORT}:3001'
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./
          target: /home/node/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  db:
    image: postgres:16
    container_name: ${PROJECT_NAME}-db
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules:

    # Documentação usada para a construção desse arquivo
    # https://www.digitalocean.com/community/tutorials/containerizing-a-node-js-application-for-development-with-docker-compose-pt
    # (principalmente o passo 4)
